apiVersion: apps/v1
kind: Deployment

metadata:
  name: namegen

spec:
  replicas: 2

  selector:
    matchLabels:
      app: namegen

  template:
    metadata:
      labels:
        app: namegen

    spec:
      containers:
      - name: namegen

        image: ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/myapps/namegen:latest

        ports:
        - containerPort: 8080

        env:
        - name: MONGO_URL
          value: mongodb://mongodb:27017/names
