apiVersion: apps/v1
kind: Deployment

metadata:
  name: namegen

spec:
  replicas: 2

  selector:
    matchLabels:
      app: namegen

  template:
    metadata:
      labels:
        app: namegen

    spec:
      containers:
      - name: namegen

        image: 605199373262.dkr.ecr.us-west-2.amazonaws.com/myapps/namegen:latest

        - name: Tag latest
          run: |
            docker tag \
            myapps/namegen:${IMAGE_TAG} \
            605199373262.dkr.ecr.us-west-2.amazonaws.com/myapps/namegen:latest

        - name: Push latest
          run: |
            docker push \
            605199373262.dkr.ecr.us-west-2.amazonaws.com/myapps/namegen:latest

        ports:
        - containerPort: 8080

        env:
        - name: MONGO_URL
          value: mongodb://mongodb:27017/names
