name: eksworkflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  cicd_job:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::605199373262:role/GitHub_OIDC_role
          role-session-name: GitHub_OIDC_role-${{ github.run_id }}

      - name: Test AWS connection
        run: aws sts get-caller-identity

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t myapps/namegen:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag myapps/namegen:$IMAGE_TAG \
          605199373262.dkr.ecr.us-west-2.amazonaws.com/myapps/namegen:$IMAGE_TAG

      - name: Push Docker image
        run: |
          docker push \
          605199373262.dkr.ecr.us-west-2.amazonaws.com/myapps/namegen:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --name namegen \
          --region us-west-2

          kubectl config current-context
          kubectl config get-contexts

      - name: Test Kubernetes access
        run: |
          kubectl auth can-i create deployment -n default
          kubectl auth can-i create service -n default
          kubectl auth can-i create configmap -n default

      - name: Update deployment image
        run: |
            sed -i "s|IMAGE_TAG|${IMAGE_TAG}|g" K8S/namegen-deployment.yaml

      - name: Deploy
        run: |
            kubectl apply -f K8S/namegen-deployment.yaml
            
      - name: Replace image tag
        run: |
          sed -i "s|IMAGE_TAG|${IMAGE_TAG}|g" K8S/namegen-deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f K8S/namegen-deployment.yaml

      - name: Describe failed pods
        if: always()
        run: |
          for pod in $(kubectl get pods -o name); do
          echo "==== $pod ===="
          kubectl describe $pod
          kubectl logs $pod --all-containers=true || true
          done

      - name: Restart deployment
        run: |
          kubectl rollout restart deployment/namegen

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/namegen --timeout=300s
